---
name: bookly
description: A new Flutter project.
publish_to: none
version: 0.1.0
environment:
  sdk: '>=3.0.6 <4.0.0'
dependencies:
  bloc: ^8.1.2
  device_preview: ^1.1.0
  flutter:
    sdk: flutter
  get: ^4.6.5
dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  build_runner:
  flutter_gen_runner:

flutter_gen:
  output: lib/core/utils
flutter:
  uses-material-design: true
  assets:
   - assets/images/Logo.png
